### ISSUE TITLE
Rename ITestRunListener3 to ITestRunListener

### ISSUE THREAD

**Issue by mickaelistria** [vrubezhny/org.eclipse.unittest#11]
Rename ITestRunListener3 to ITestRunListener

**Comment by vrubezhny** [comment]
A confusion is possible between this `org.eclipse.unittest.model.ITestRunListener3` interface and `org.eclipse.unittest.TestRunListener` class which are not related.  
Probably a better name is to be found for the `TestRunListener` class also.
