### ISSUE TITLE
Remove testRunListener extension point

### ISSUE THREAD

**Issue by mickaelistria** [vrubezhny/org.eclipse.unittest#21]
We currently don't have use case for this extension point, and the only listener at the moment is internal. So let's remove the extension point.

**Comment by vrubezhny** [comment]
This makes Unit Test View plug-in to be started in "early"-like manner without explicitly defining  the plug-in's early startup options. It's like the plug-in will be loaded and the Unit test View will be shown on a first Unit Test Runner start.
This approach, as far as I understand, allows not to consume any resources by the Unit Test Plug-in (memory, CPU and so on) until it''s really required (a test is started) or a user explicitly opens the Unit Test View.

**Comment by mickaelistria** [comment]
> This makes Unit Test View plug-in to be started in "early"-like manner

How so? Why is an early loading required anyway?
The Unit Test view plugin will be loaded by any plugin that references it (eg uses its API or even just uses the UnitTestLaunchConfigurationConstants), so we probably don't need extra-enablement.

And even if we do need early-startup (which I don't think is needed here), then the proper way to achieve it is to use the startup extension point, not to add another extension point and a set of APIs.

**Comment by mickaelistria** [comment]
See proposal at https://github.com/vrubezhny/org.eclipse.unittest/pull/27

**Comment by mickaelistria** [comment]
Done.
