### ISSUE TITLE
Unit Test View bundle is not auto-activated at first unit test run 

### ISSUE THREAD

**Issue by vrubezhny** [vrubezhny/org.eclipse.unittest#48]
The Unit Test bundle is to be activated at the time of the first start of a Unit Test runner i order to allow its model to properly gather all the changes and display the results into the Unit Test View.
Currently it doesn't happen - when test is started for the first time - the view is not shown/updated with the test results.
Once a user opens the Test View - it starts to be activated/updated automatically  on each following test run.

![UnitTestView-Not-Activated](https://user-images.githubusercontent.com/620781/95399301-2d570c80-0908-11eb-8e33-1399d888e827.gif)

**Comment by mickaelistria** [comment]
We'd need the launchDelegate to ensure the view is visible.
Either they can call `Platform.getBundle("org.eclipse.unittest").start()`, or they can try to dereference some API mehod. I suggest we add a method `ITestViewSupport.ensureBundleStarted()`. @vrubezhny what do you think?
