### ISSUE TITLE
Need to change label for dynamically added root test suite elements

### ISSUE THREAD

**Issue by vrubezhny** [vrubezhny/org.eclipse.unittest#52]
Currently the label for a root test suite that is added a a dynamic one displays "Unrooted Tests" text. We shouldn't have this to be displayed.

![unrooted-root-testsuite](https://user-images.githubusercontent.com/620781/95845113-10786a00-0d4a-11eb-8fa6-a8b363f62fcd.png)

**Comment by mickaelistria** [comment]
I don't think we need to change the label dynamically, but instead just make the default label nicer.

**Comment by vrubezhny** [comment]
Then let's close this one without a fix in favour of https://github.com/vrubezhny/org.eclipse.unittest/issues/55
