### ISSUE TITLE
Remove project from ITestRunSession

### ISSUE THREAD

**Issue by mickaelistria** [vrubezhny/org.eclipse.unittest#6]
It seems to me we can assume that all tests will have a launch, and that launch don't require to have a project. We may also want to run tests for content that is not in a project.
So instead of keeping a reference to the project, we should instead just keep the reference to the launch (already there) and let extensions that need it dereference the launch to get the project.

**Comment by vrubezhny** [comment]
We need IProject on serialization/deserialization for a test run session - where no ILanch nor ILaunchConfiguration is serialized, so on deserialization we cannot restore it to a new TestRunSession object instance.
Do you know if it's easy to serialize some launch or launch config identifier in order to seek a launch by this identifier on deserialization?

**Comment by mickaelistria** [comment]
What are the user stories that we want to support which don't or cannot involve an ILaunch or ILaunchConfiguration deserialization? Also (de)serialization seems only necessary between restarts of the IDE, while we're on the same instance, it's better to keep references directly.

**Comment by vrubezhny** [comment]
@mickaelistria Could you please review the PR #12?

When a test run session is terminated (for whatever reason) it gets swapped out (written) to a file. When a new test run session is about to be created it gets swapped in (read) from a file (if exists), so in theory it should show the previous run results.

**Comment by vrubezhny** [comment]
The PR #12 is merged.
However, I'm reopening the issue in order to evaluate other opportunities to reduce coupling on project.

**Comment by mickaelistria** [comment]
I don't see any reference to IProject left in the main unittest bundle. Cool!
