### ISSUE TITLE
Contribute to Eclipse Platform

### ISSUE THREAD

**Issue by mickaelistria** [vrubezhny/org.eclipse.unittest#65]
It seems to be the right time to contribute this code to Eclipse.org.
* `org.eclipse.unittest` should be pushed as a Gerrit review to eclipse.platform.debug repo
* `org.eclipse.unittest.junit` should be pushed as a Gerrit review to eclipse.jdt.ui repo (Platform usually mandates that 1 consumer is inside the SDK)
The contribution should be a single commit for each repository. It's best if author/submitter is @vrubezhny but the commit will also need to mention `Also-By: Mickael Istria <mistria@redhat.com>` in the footer.

CDT and Corrosion content can remain in this repo at the moment, we'll try to migrate them later when there is enough progress on Platform side.

**Comment by vrubezhny** [comment]
A Gerrit change created for Platform Debug: https://git.eclipse.org/r/c/platform/eclipse.platform.debug/+/171116

**Comment by vrubezhny** [comment]
A Gerrit change created for JDT UI: https://git.eclipse.org/r/c/jdt/eclipse.jdt.ui/+/171126 (for org.eclipse.unittest.junit bundle)

**Comment by mickaelistria** [comment]
I think we can close this one since contribution is now tracked on Eclipse Bugzilla and Gerrit.
