### ISSUE TITLE
Rename unitTestKind extension point and ITestKind/TestKind API

### ISSUE THREAD

**Issue by mickaelistria** [vrubezhny/org.eclipse.unittest#7]
This name is already used by JUnit API so reusing it is confusing.
Moreover, what we are trying to achive with the view is a subset of the whole JUnit extensions; so we should retitle it to something more specific like `unitTestViewSupport`.

**Comment by vrubezhny** [comment]
How about to rename it to IUnitTestinfo/UnitTestInfo (or just to ITestInfo/TestInfo) as it really about specifying the references to a Test Runner Client and a Test View Support instances for a specified test?

**Comment by mickaelistria** [comment]
I'm not sure info is the best term as it doesn't really explain what it does. I'm wondering whether it couldn't be just a UnitTestViewSupport, and this support would be responsible for providing a TestRunnerClient as a `getTestRunnerClient()` method. What do you think?

**Comment by vrubezhny** [comment]
It's just that the "main" thing here is TestRunnerClient. UnitTest View Support is an utility class that helps to Unit Test View to create some action... The view itself will not stop working without having those actions, while it is really useless without a Test Runner Client. So, I agree to merge `getTestRunnerClient()` API method and the contents of TestViewSupport into some new interface, but using `ITestViewSupport` as a target for this, imho, is to put the things up-side-down.

`ITestKind` was used to describe a Test Run - which Test Runner to use, how to create a launch and  then, after all, which actions to add (test view support) to the test view containing the results of testing. So, imho `TestViewSupport` not the best choice for the name to rename `ItestKind` to.

**Comment by mickaelistria** [comment]
What about
```xml
  <extension point="org.eclipse.unittest">
     <viewSupport id="..." class="..."/>
  </extension>
```
?

**Comment by mickaelistria** [comment]
I think the extension point needs to be further improved:  `_` is not really the convention for extension point schema, camelCase is preferred

**Comment by mickaelistria** [comment]
Fixed.
