### ISSUE TITLE
Make re-run rely more on launch/launch configuration

### ISSUE THREAD

**Issue by mickaelistria** [vrubezhny/org.eclipse.unittest#8]
Re-run actions seems to leverage ILaunchConfiguration at some point (re-running is basically about getting a launch config and tweaking it to add some arguments or use an alternative launch type). However, this doesn't surface well in the RerunAction API. We should aim at simplifying that, for example by making the `ITestViewSupport.getRerunActions()` return a list of ILaunchConfiguration already tweaked by the client according to the selection.

**Comment by vrubezhny** [comment]
Fixed with PR #16 (Rerun to launchconfig #16)
